### ISSUE TITLE
format values is much needed option

### ISSUE THREAD

**Issue by yogitapatil62** [hski-github/spotfire-scrollable-bar-chart#12]
<img width="675" alt="image" src="https://github.com/hski-github/spotfire-scrollable-bar-chart/assets/138801625/b9a6a38d-942e-4c06-9d01-5f2c2d52bafb">

**Comment by hski-bayer** [comment]
Hello! How about using the Round() function as a custom expression for the value axis? https://docs.tibco.com/pub/spotfire/7.0.1/doc/html/ncfe/ncfe_math_functions.htm

**Comment by yogitapatil62** [comment]
That’s really helpful…It worked for me.

**Comment by hski-github** [comment]
Okay, nice :-). Closing this issue then.
