### ISSUE TITLE
Show pointer cursor when hovering scale and values

### ISSUE THREAD

**Issue by arnaudspotfire** [hski-github/spotfire-scrollable-bar-chart#7]
The mod setting are reachable by clicking on the scale or values but the mouse cursor does not change which makes the settings a bit hidden. My advise would be to show a pointer cursor or add a setting button.

**Comment by hski-github** [comment]
You mean like adding something like `cursor: pointer;` to the css for `table#tabularbarchart{ ... }`? Could you check if this does the job? 

Would like to avoid a gear icon somewhere. Actually I thought this would be pointer already. Could you provide a screenshot?

**Comment by arnaudspotfire** [comment]
Yes I mean exactly something like a `cursor: pointer`

**Comment by hski-github** [comment]
Okay, looks like also browsers behave slightly different. On macOS both Chrome and Firefox show default, but Safari shows text selector.

**Comment by hski-github** [comment]
Also some browsers inherit user-select setting to child elements, other not https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by hski-github** [comment]
Decided to keep user select as is.

**Comment by hski-github** [comment]
Changed to pointer with latest commit as version 1.0.1
